"""fixing foreign keys

Revision ID: 05bb301a1930
Revises: 484284b2c0ac
Create Date: 2026-03-02 06:27:51.434798

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "05bb301a1930"
down_revision: str | Sequence[str] | None = "484284b2c0ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
