"""adding due dates to assignments

Revision ID: 436604a515bd
Revises: 447721779876
Create Date: 2026-02-27 03:57:09.872700

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "436604a515bd"
down_revision: str | Sequence[str] | None = "447721779876"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments", sa.Column("due_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "due_date")
    # ### end Alembic commands ###
