"""inserting title, question, and description to assignments

Revision ID: 447721779876
Revises: 5799e3b8096d
Create Date: 2026-02-27 03:54:55.340891

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "447721779876"
down_revision: str | Sequence[str] | None = "5799e3b8096d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments", sa.Column("title", sa.String(length=255), nullable=False)
    )
    op.add_column("assignments", sa.Column("question", sa.Text(), nullable=False))
    op.add_column("assignments", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "description")
    op.drop_column("assignments", "question")
    op.drop_column("assignments", "title")
    # ### end Alembic commands ###
