"""renaming feedback_text to transcribed text in Transcription

Revision ID: a59d68f2afa9
Revises: d6b4ed6615e1
Create Date: 2026-02-27 17:31:07.524601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59d68f2afa9'
down_revision: Union[str, Sequence[str], None] = 'd6b4ed6615e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('transcribed_text', sa.Text(), nullable=True))
    op.drop_column('transcriptions', 'feedback_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('transcriptions', 'transcribed_text')
    # ### end Alembic commands ###
