"""Adding visible_at column

Revision ID: d2540b3257a7
Revises: a3f8e1c2d4b6
Create Date: 2026-04-08 09:59:34.618087

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2540b3257a7"
down_revision: str | Sequence[str] | None = "a3f8e1c2d4b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column("visible_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "visible_at")
    # ### end Alembic commands ###
