"""testcases per assignment not submission

Revision ID: f6da871e544a
Revises: 436604a515bd
Create Date: 2026-02-27 04:25:20.281326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6da871e544a"
down_revision: str | Sequence[str] | None = "436604a515bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("testcases", sa.Column("assignment_id", sa.Integer(), nullable=False))
    op.add_column("testcases", sa.Column("expected_output", sa.Text(), nullable=False))
    op.drop_constraint(
        op.f("testcases_submission_id_fkey"), "testcases", type_="foreignkey"
    )
    op.create_foreign_key(None, "testcases", "assignments", ["assignment_id"], ["id"])
    op.drop_column("testcases", "suggested_output")
    op.drop_column("testcases", "submission_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testcases",
        sa.Column("submission_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "testcases",
        sa.Column("suggested_output", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "testcases", type_="foreignkey")
    op.create_foreign_key(
        op.f("testcases_submission_id_fkey"),
        "testcases",
        "submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_column("testcases", "expected_output")
    op.drop_column("testcases", "assignment_id")
    # ### end Alembic commands ###
